# /usr/bin/firefox
/usr/bin/abiword
/usr/bin/atril
/usr/bin/celluloid
# ImageMagick
/usr/bin/convert-im6.q16
/usr/bin/display-im6.q16
/usr/bin/drawing
/usr/bin/evince
/usr/bin/pix
/usr/bin/vlc
/usr/bin/xfimage
/usr/bin/xreader
/usr/bin/xviewer
/usr/bin/eog
